version: 0.2
env:
  shell: bash
  variables:
    STORAGE_BUCKET: arqgen-blockparty
    MINICONDA: Miniconda3-py38_23.3.1-0-Linux-x86_64.sh
    GITHUB_ARQBOT_USER: arqgen-bot
  secrets-manager:
    GITHUB_ARQBOT_PAT: "CROSS_ROLE:GITHUB_ARQBOT_PAT"
    SONAR_TOKEN: 'SONAR_TOKEN:SONAR_TOKEN_ARQ_COMMON'
phases:
  install:
    commands:
      - aws s3 cp --no-progress s3://arqgen-blockparty/tools/prebuild.sh /root/prebuild.sh
      - chmod +x /root/prebuild.sh
      - /root/prebuild.sh
      - git config --global url."https://${GITHUB_ARQBOT_USER}:${GITHUB_ARQBOT_PAT}@github.com/arqgen/".insteadOf git@github.com:arqgen/


  build:
    commands:
      - export PATH=/root/miniconda3/bin/:$PATH
      - conda info
      - touch $CODEBUILD_SRC_DIR/py/out.txt
      - conda create --prefix ./venv python=3.11 -y -q || (rm -rf venv; rm -rf /root/miniconda3/pkgs/* ;  rm -rf /root/.conda/pkgs/* ; conda create --prefix ./venv python=3.11 -y -q)
      - |
        eval "$(conda shell.bash hook)"
        conda activate $CODEBUILD_SRC_DIR/venv
        pip install poetry pytest 
        cd $CODEBUILD_SRC_DIR/py
        poetry install --with=test
      - |
        set -o pipefail
        eval "$(conda shell.bash hook)"
        conda activate $CODEBUILD_SRC_DIR/venv
        cd $CODEBUILD_SRC_DIR/py
        pip install pytest-cov flaky
        PYTHONPATH=. pytest --force-flaky --max-runs=5 --no-flaky-report --cov-report xml --cov-report term --cov=persistente | tee out.txt
  post_build:
    commands:
      - |
        if [ "${CODEBUILD_WEBHOOK_TRIGGER:0:2}" = "pr"  ] 
        then
          [[ $CODEBUILD_BUILD_SUCCEEDING = 1 ]] && STATUS="Success" || STATUS="Fail"
          COVER=$(cat $CODEBUILD_SRC_DIR/py/out.txt |grep TOTAL|awk '{ print $4}')
          OWNER=$(echo $CODEBUILD_SRC_DIR | awk 'BEGIN {FS = "/"} {print $(NF-1)}')
          REPO=$(echo $CODEBUILD_SRC_DIR | awk 'BEGIN {FS = "/"} {print $(NF)}')
          PR=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -b4- )
          echo "TOTAL COVERAGE: $COVER"
          $(jq --null-input \
            --arg body "TOTAL COVERAGE: $COVER $STATUS" \
            '{"event": "COMMENT", "body": $body}' > file_to_send)
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_ARQBOT_PAT"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/pulls/$PR/reviews \
              --data-binary @file_to_send
        fi
cache:
  paths:
    - "/root/.cache/pypoetry/**/*"
    - "/root/miniconda3/pkgs/**/*"
reports:
  test-group:
    file-format: COBERTURAXML
    files:
      - "coverage.xml"
